### ISSUE TITLE
NVDBAPI2GML_V2_2017.fmw står og spinner

### ISSUE THREAD

**Issue by geogaard** [jetgeo/NVDBGML#11]
Jeg opplever at NVDBAPI2GML_V2_2017.fmw ikke stopper, selv om gml-fila er skrevet ferdig. Det er akkurat som om workspacet er i en endeløs loop. Har du opplevd dette?

**Comment by geogaard** [comment]
![image](https://user-images.githubusercontent.com/3242373/35102273-bce099a8-fc62-11e7-880e-e1f0f0fa2821.png)

Det fungerer etter å ha satt stien til csv-fila på nytt. Kan den settes relativt i FME?

**Comment by geogaard** [comment]
Det ser ut til å gjelde alle refererte csv-filer i både joinere og schemamappere

**Comment by jetgeo** [comment]
Stiene skal egentlig være satt relativt, har nok skjedd noe krøll i originalen hos meg. Bra at du oppdaga det og fant en løsning. Skal fikse det og laste opp ny fil, men rekker det ikke denne uka.
Og artig at noen faktisk bruker det :).

**Comment by geogaard** [comment]
Har oppdatert de to NVDBAPI2GML-workspacene tli FME 2018 og lagt til et script som finner stien til CSV mappa. Jeg kan sende en pull request, men da må jeg kanskje få mulighet til å bidra? Har ikke gjort det før så er litt usikker på gangen i det. Jeg får ikke lov til å lag en branch heller.

**Comment by jetgeo** [comment]
Har invitert deg inn nå, får du mulighet til å gjøre mer da?

**Comment by geogaard** [comment]
Ja, nå har jeg muligheter. Må bare finne ut hvordan jeg skal gjøre dette for eksempel lage en ny branch med oppdaterte filer slik at du kan se på det. Så en pull request når det er klart?

**Comment by jetgeo** [comment]
Ja, jeg tror du må lage en pull request.

**Comment by jetgeo** [comment]
Tror det funka. Her ser vi nytteverdien av samarbeidsverktøy som GitHub :).

**Comment by geogaard** [comment]
Det ser bra ut. Må bare enable GML skriveren i NVDBAPI2GML_V2_2017.fmw, jeg som glemte å gjøre det før jeg commitet. Gøy det her @jetgeo

**Comment by jetgeo** [comment]
Ok, fikser du det i en ny pull request?

**Comment by geogaard** [comment]
Nå prøvde jeg å kjøre en ny commit på master for å rette den

**Comment by jetgeo** [comment]
Supert, ser bra ut.
