### ISSUE TITLE
æøå i attributtnavn

### ISSUE THREAD

**Issue by jetgeo** [jetgeo/NVDBGML#13]
Ser ut til at det har oppstått et problem i FME 2018 som ikke var der i FME 2017?

Python-scriptet klarer ikke å tolke æøå riktig, dermed blir attributtnavnene for lineære posisjoner forvrengt:
![image](https://user-images.githubusercontent.com/7501876/36482400-78440408-1713-11e8-9a8f-01cc66bc06f9.png)

Har du kjennskap til noen løsning på dette, @geogaard ?

**Comment by geogaard** [comment]
Jeg skal prøve å gjenskape problemet her, så kan jeg høre med Safe om det har skjedd noen endringer koding av norske tegn.

**Comment by geogaard** [comment]
Får samme feil, men den kan unngås ved å sette en u foran strengen:  

> feature.setAttribute(u'lineærPosisjon{%d}...

Har uansett rapport det som en feil og satt deg på kopi. Jeg har rettet versjonen her med 2018 RC, hvordan vil du gå fram for oppdatering. Det er jo litt kronglete med alle de forskjellige versjonene av FME.

**Comment by jetgeo** [comment]
Takk, ser ut til å fungere. Angir den u-en rett og slett at teksten skal tolkes som unicode? 
Oppdaterer lokalt hos meg også, og laster opp en versjon etterhvert. Når det gjelder versjoner av FME tenker jeg at det som legges kan være basert på nyeste versjon. Men jeg må antakelig rydde litt, ligger litt gammelt grums her og der.

**Comment by geogaard** [comment]
Stemmer, det.

> In Python source code, Unicode literals are written as strings prefixed with the ‘u’ or ‘U’ character: u'abcdefghijk'.

[Unicode HOWTO](https://docs.python.org/2/howto/unicode.html)

Bra det var en enkel fiks da:)

**Comment by jetgeo** [comment]
Glimrende, lukker saken.
